### PR TITLE
BESRelevanceProvider shared processor updates

### PR DESCRIPTION
**Pull request by blimvisible**
Updated BESRelevanceProvider to use shared processor on four download recipes.

### CODE REVIEW

**Comment by jgstew** [comment]
Looks good, though it looks like you added a newline at the end of every file or removed it, or something?

It is not a reason to reject the PR, just something I noticed.

**Comment by blimvisible** [comment]
> Looks good, though it looks like you added a newline at the end of every file or removed it, or something?

Apparently my text editor (nano) took out the newlines -- I didn't do it intentionally.

**Comment by hansen-m** [comment]
Looks good! Thanks for the help. I'm not too worried about the last lines, probably should have them.

**Comment by jgstew** [comment]
I didn't figure the newline stuff was intentional. I've definitely had that happen before with various editors.

I feel like having a newline at the end of a file is one of the lesser things, but potentially a similar religious war like tabs vs spaces.

Ultimately I think consistency is more important than what the state is, with most of the files eventually being normalized one way or the other and not have it go back and forth in the history.

**Comment by blimvisible** [comment]
I'll keep an eye out for things like that in the future, and hopefully pick up other aspects of git etiquette (gitiquette?) in time.

**Comment by jgstew** [comment]
Well it does seem like your change was for the better if it caused these files to align better with the other files in the repo. I'm mostly thinking out loud about something minor I haven't thought about in a while.

I'm thinking along the lines of something like `pylint` but for code files in a repo in general. If they almost all end with newlines, then flag the ones that don't, or of most don't end in newlines, then flag the ones that do so that it is easier to normalize them. Similar for files that end in multiple newlines.

The next level would be to check code across all of github and rate it for consistency based upon **tabs** vs **spaces** and **ending-newline** vs **no-ending-newline**.

**Pull request merged**
