### PR TITLE
Change Process from dict to array

### PR DESCRIPTION
**Pull request by homebysix**

### CODE REVIEW

**Comment by jgstew** [comment]
Took me a second to figure out what was going on here.

This is changing "Process" from an empty dictionary to an empty array.

**Comment by homebysix** [comment]
Yep, it's mostly a cosmetic change.

`Process` should always be an array, but the template "shared processor" recipe on autopkg/recipes was incorrectly using a dictionary. That shouldn't cause any failures unless the shared processor stub recipe is called directly (which it shouldn't be, in normal usage). This PR just eliminates that rare edge case.

**Comment by jgstew** [comment]
That makes a lot of sense.

Here is the related commit to the original template: https://github.com/autopkg/recipes/commit/c68fbf9b3794fac5d281cc357035a4ad564107ad

**Comment by hansen-m** [comment]
Thanks, guys!

**Pull request merged**
