### PR TITLE
Update MeshLab download recipe

### PR DESCRIPTION
**Pull request by rustymyers**
Utilizes SourceForgeURLProvider.py to find latest download URL

### CODE REVIEW

**Comment by rustymyers** [comment]
Adding recipe for Windows

**Comment by jgstew** [comment]
What is the original source of `SourceForgeURLProvider.py` ?

**Comment by rustymyers** [comment]
Not sure of the original author. Perhaps @ jessepeterson?
https://github.com/jessepeterson/autopkg-recipes

**Comment by jgstew** [comment]
I definitely go back and forth on this. Do I copy all dependencies locally and manage them myself to help prevent breakage? But then what happens when improvements are made to the original? Then things become complicated. 

In either case, the original source should be at least referenced for attribution somewhere. 

It isn't obvious who the originator was, but from this discussion, it does seem to be @ jessepeterson : https://github.com/autopkg/timsutton-recipes/issues/8

**Comment by rustymyers** [comment]
Agreed on all counts. I had found the code last year and didn't get around to touching it till today. 

It seems there should be a repo specifically to maintain these tools in a central location, but I'm not aware of a method to do this with AutoPkg or the existence of one.

**Comment by jgstew** [comment]
There are ways to make use of shared processors without having to copy them entirely into the location of the particular recipe. 

I don't have much experience with it, but it is something @hansen-m does have experience with.

It might be partially up to the original author of the processor to craft it in such a way that it can be shared more easily, and I don't know if that is the case here.

I think there is another option, in which you can actually have a pointer to the file in a separate GIT repo, so that the file actually stays in it's source repo, but has a sort of virtual copy here.

**Comment by jgstew** [comment]
I should point out that this is a minor issue overall as far as current functionality goes, it just may become a problem in the future. Definitely worth noting if nothing else.

**Comment by rustymyers** [comment]
Here's a task I found that points to a SourceForgeURLProvider.py in another repo: https://github.com/autopkg/homebysix-recipes/blob/master/GrandPerspective/GrandPerspective.download.recipe

Perhaps this should be the method for using the provider but does require adding the repo first.

**Comment by hansen-m** [comment]
I think using the shared recipe processors is the recommended way to go. Any changes to the processor are more likely to fix rather than break something. The nature of autopkg is to test often and routinely fix things as vendors make changes.

**Comment by rustymyers** [comment]
I've updated the recipes to utilize the shared processor.

**Comment by jgstew** [comment]
Neat!

Do you have to 'install' the processor for it to work? I'm still a tad unclear how shared processors work if you are running a recipe that uses one for the first time and you don't have it.

**Comment by rustymyers** [comment]
I believe you'll need to be subscribed to the repo the shared processor is in, but that's it. It seems to find the processor based on the recipe's identifier. I'd be interested in creating a repo that is only shared processors, as I think that could be beneficial in the long run.

**Comment by jgstew** [comment]
That is pretty cool if you just need to add the repo as a whole, and then it just works.

Using more autopkg is on my list of things to do that I never seem to get to.   :(

**Pull request merged**
