### PR TITLE
[Anaconda] Add ability to choose version

### PR DESCRIPTION
**Pull request by cwhits**
There is a 2.7 version of Anaconda and (currently) a 3.5 version of Anaconda. The packages provided by Anaconda are named using the Python major version only, i.e., Anaconda2 and Anaconda3. These versions just set the Python version used for the default environment.

I added `PYTHON_MAJOR_VERSION` so you can set whether you want Anaconda2 or Anaconda3. I set the default to 3 but I'd be glad to switch it to 2 if you'd prefer.

I was having trouble setting `NAME` as `Anaconda%PYTHON_MAJOR_VERSION%` as it wouldn't expand the major version variable, so I added the `PKG_NAME` variable to keep from typing `%NAME%%PYTHON_MAJOR_VERSION%` repeatedly. 

I also got rid of the user agent since they now use an anchor for selecting which OS's downloads you want to view.

I added `PYTHON_VERSION` (which grabs the full Python version) and `ANACONDA_VERSION` so they could be used in later on, if needed.

```
$ autopkg run Anaconda.download.recipe -v
Processing Anaconda.download.recipe...
WARNING: Anaconda.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
URLTextSearcher: Found matching text (PYTHON_VERSION): 3.5
URLTextSearcher: Found matching text (match): 3.5
URLTextSearcher
URLTextSearcher: Found matching text (url): https://repo.continuum.io/archive/Anaconda3-4.2.0-MacOSX-x86_64.pkg
URLTextSearcher: Found matching text (match): https://repo.continuum.io/archive/Anaconda3-4.2.0-MacOSX-x86_64.pkg
URLTextSearcher: Found matching text (ANACONDA_VERSION): 4.2.0
URLDownloader
URLDownloader: Storing new Last-Modified header: Tue, 18 Oct 2016 00:33:47 GMT
URLDownloader: Storing new ETag header: "58056deb-19711c48"
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.hansen-m.download.Anaconda/downloads/Anaconda3.pkg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "Anaconda3.pkg":
CodeSignatureVerifier:    Status: signed by a certificate trusted by Mac OS X
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: CONTINUUM ANALYTICS INC (Z5788K4JT7)
CodeSignatureVerifier:        SHA1 fingerprint: 88 57 F2 81 D2 DC 1A 7E F0 FA F5 2C A0 B3 86 80 D1 70 BA C0
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
CodeSignatureVerifier:
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
Receipt written to /Users/cwhits/Library/AutoPkg/Cache/com.github.hansen-m.download.Anaconda/receipts/Anaconda.download-receipt-20170104-154430.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/cwhits/Library/AutoPkg/Cache/com.github.hansen-m.download.Anaconda/downloads/Anaconda3.pkg
```

### CODE REVIEW

**Comment by cwhits** [comment]
Here's running it with the other version:
```
$ autopkg run Anaconda.download.recipe -v -k PYTHON_MAJOR_VERSION=2                                                        
Processing Anaconda.download.recipe...
WARNING: Anaconda.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
URLTextSearcher: Found matching text (PYTHON_VERSION): 2.7
URLTextSearcher: Found matching text (match): 2.7
URLTextSearcher
URLTextSearcher: Found matching text (url): https://repo.continuum.io/archive/Anaconda2-4.2.0-MacOSX-x86_64.pkg
URLTextSearcher: Found matching text (match): https://repo.continuum.io/archive/Anaconda2-4.2.0-MacOSX-x86_64.pkg
URLTextSearcher: Found matching text (ANACONDA_VERSION): 4.2.0
URLDownloader
URLDownloader: Storing new Last-Modified header: Tue, 18 Oct 2016 00:33:11 GMT
URLDownloader: Storing new ETag header: "58056dc7-193e0762"
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.hansen-m.download.Anaconda/downloads/Anaconda2.pkg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "Anaconda2.pkg":
CodeSignatureVerifier:    Status: signed by a certificate trusted by Mac OS X
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: CONTINUUM ANALYTICS INC (Z5788K4JT7)
CodeSignatureVerifier:        SHA1 fingerprint: 88 57 F2 81 D2 DC 1A 7E F0 FA F5 2C A0 B3 86 80 D1 70 BA C0
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
CodeSignatureVerifier:
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
Receipt written to /Users/cwhits/Library/AutoPkg/Cache/com.github.hansen-m.download.Anaconda/receipts/Anaconda.download-receipt-20170105-102603.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/cwhits/Library/AutoPkg/Cache/com.github.hansen-m.download.Anaconda/downloads/Anaconda2.pkg

```

**Comment by jgstew** [comment]
This looks good overall. If this used to only do Anaconda2 then it seems like that should be the default to prevent breakage. Does this have any other breaking issues for a user of the previous recipe?

**Comment by cwhits** [comment]
The package downloaded will now either be `Anaconda2.pkg` or `Anaconda3.pkg` instead of `Anaconda.pkg`.

That has me thinking if I should change the way it names the download since if you change the `name` with a recipe override, it'll still add the 2 or 3 to the downloaded `.pkg`.

So the issue I was having before was that if I set the name to `Anaconda%PYTHON_MAJOR_VERSION%` it would name the downloaded pkg literally `Anaconda%PYTHON_MAJOR_VERSION%` instead of expanding the variable and naming it `Anaconda2.pkg`. I haven't tried setting `PKG_NAME` to `Anaconda` and setting the name to `%PKG_NAME%%PYTHON_MAJOR_VERSION%`.

Thoughts?

**Comment by cwhits** [comment]
Example of setting the `name` to `Anaconda%PYTHON_MAJOR_VERSION%`:

```$ autopkg run Anaconda.download -vv
Processing Anaconda.download...
WARNING: Anaconda.download is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': u'Python (?P<PYTHON_VERSION>3\\.\\d) version',
           'url': u'https://www.continuum.io/downloads#osx'}}
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Found matching text (PYTHON_VERSION): 3.5
URLTextSearcher: Found matching text (match): 3.5
{'Output': {u'PYTHON_VERSION': '3.5', 'match': '3.5'}}
URLTextSearcher
{'Input': {'CURL_PATH': '/usr/bin/curl',
           're_pattern': u'(?P<url>https\\://repo\\.continuum\\.io/archive/Anaconda%PYTHON_MAJOR_VERSION%-(?P<ANACONDA_VERSION>[0-9.]+)-MacOSX-x86_64\\.pkg)',
           'result_output_var_name': 'match',
           'url': u'https://www.continuum.io/downloads#osx'}}
No match found on URL: https://www.continuum.io/downloads#osx
Failed.
Receipt written to /Users/cwhits-admin/Library/AutoPkg/Cache/com.github.hansen-m.download.Anaconda/receipts/Anaconda-receipt-20170105-141858.plist

The following recipes failed:
    Anaconda.download
        Error in com.github.hansen-m.download.Anaconda: Processor: URLTextSearcher: Error: No match found on URL: https://www.continuum.io/downloads#osx

Nothing downloaded, packaged or imported.
```

It appears that variables won't expand in `name`.

**Comment by hansen-m** [comment]
@cwhits Very cool! Thanks for doing this. II'm fine with defaulting to either version, I'll just have to make an override for the other. I get what @jgstew is saying, and defaulting to 2 would be better practice. I don't actually see any other child recipes using this, what software deployment tool are you using?

You're right, autopkg doesn't do variable substitution within the input variables so the package name variables would have to be set in the processor input directly, making them unchangeable. I usually use %pathname% anyway so it wouldn't break my child recipe but I think just standardizing on a naming convention (and removing it from the input/overrides) would be fine.

**Comment by cwhits** [comment]
So besides defaulting to 2, should I stick with the janky `PKG_NAME` being set to  `%NAME%%PYTHON_MAJOR_VERSION%`?

I'm going to be creating a munki recipe but was waiting for this to be accepted so I know what I'll be working with 🙂

**Comment by hansen-m** [comment]
My vote is to either just remove %PKG_NAME% from the recipe input and move the same pattern down to the URLDownloader: 

```
        <dict>
            <key>Processor</key>
            <string>URLDownloader</string>
            <key>Arguments</key>
            <dict>
                <key>url</key>
                <string>%url%</string>
                <key>filename</key>
                <string>%NAME%%PYTHON_MAJOR_VERSION%-%version%.pkg</string>
            </dict>
        </dict>
```

Or just exclude the `filename` key altogether so it defaults to the tail of the URL `Anaconda2-4.2.0-MacOSX-x86_64.pkg`

Either is fine by me, and I think other download recipes do it both ways. The latter makes it very clear what it is but also maybe makes it slightly more difficult to for subsequent processors if they don't use the %pathname% variable. 

My only other concern is that I think %version% should be set to the version of the software being downloaded to fit the autopkg variable naming conventions. It looks like you just have `ANACONDA_VERSION` set.

**Comment by cwhits** [comment]
latest commit:

```
$ autopkg run Anaconda.download -v
Processing Anaconda.download...
WARNING: Anaconda.download is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
URLTextSearcher: Found matching text (PYTHON_VERSION): 2.7
URLTextSearcher: Found matching text (match): 2.7
URLTextSearcher
URLTextSearcher: Found matching text (url): https://repo.continuum.io/archive/Anaconda2-4.2.0-MacOSX-x86_64.pkg
URLTextSearcher: Found matching text (version): 4.2.0
URLTextSearcher: Found matching text (match): https://repo.continuum.io/archive/Anaconda2-4.2.0-MacOSX-x86_64.pkg
URLDownloader
URLDownloader: Storing new Last-Modified header: Tue, 18 Oct 2016 00:33:11 GMT
URLDownloader: Storing new ETag header: "58056dc7-193e0762"
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.hansen-m.download.Anaconda/downloads/Anaconda2-4.2.0.pkg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "Anaconda2-4.2.0.pkg":
CodeSignatureVerifier:    Status: signed by a certificate trusted by Mac OS X
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: CONTINUUM ANALYTICS INC (Z5788K4JT7)
CodeSignatureVerifier:        SHA1 fingerprint: 88 57 F2 81 D2 DC 1A 7E F0 FA F5 2C A0 B3 86 80 D1 70 BA C0
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
CodeSignatureVerifier:
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
Receipt written to /Users/cwhits/Library/AutoPkg/Cache/com.github.hansen-m.download.Anaconda/receipts/Anaconda-receipt-20170109-150704.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/cwhits/Library/AutoPkg/Cache/com.github.hansen-m.download.Anaconda/downloads/Anaconda2-4.2.0.pkg
```

**Comment by hansen-m** [comment]
@cwhits Thanks again for working on this! I really appreciate the pull request.

**Pull request merged**
